name: build exer4

on:
  workflow_dispatch

jobs:
  build:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v4.0.2
      #   with:
      #     node-version: '20.x'
        
      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: buildCache
          
      - name: Install dependencies
        run: npm ci
        
      - name: Code Coverage
        run: npm test -- --coverage
        env:
          CI: true
          
      - name: Upload code coverage
        uses: actions/upload-artifact@v4.3.3
        with:
          name: codecoverage
          path: coverage
          
      - name: build
        run: npm run build
        
      - name: Upload build files
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build
          path: build
          
